model_id = "mlx-community/MiniMax-M2.1-8bit"
revision = "3d779130c25f54aa9198da1c845d844de7acc086"
n_layers = 61
hidden_size = 3072
supports_tensor = true
tasks = ["TextGeneration"]
family = "minimax"
quantization = "8bit"
base_model = "MiniMax M2.1"
capabilities = ["text", "thinking", "thinking_toggle"]

[storage_size]
in_bytes = 242986745856
