model_id = "mlx-community/Qwen3-30B-A3B-4bit"
revision = "d388dead1515f5e085ef7a0431dd8fadf0886c57"
n_layers = 48
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
family = "qwen"
quantization = "4bit"
base_model = "Qwen3 30B"
capabilities = ["text", "thinking", "thinking_toggle"]

[storage_size]
in_bytes = 17612931072
