model_id = "mlx-community/Meta-Llama-3.1-8B-Instruct-4bit"
revision = "241a666dad6cb93c8ff213d39a7f34a36bf26db4"
n_layers = 32
hidden_size = 4096
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "4bit"
base_model = "Llama 3.1 8B"
capabilities = ["text"]

[storage_size]
in_bytes = 4637851648
