model_id = "mlx-community/Llama-3.2-3B-Instruct-8bit"
revision = "ff054899609078569493def2823f9acd2780c0c9"
n_layers = 28
hidden_size = 3072
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "8bit"
base_model = "Llama 3.2 3B"
capabilities = ["text"]

[storage_size]
in_bytes = 3501195264
