model_id = "mlx-community/Llama-3.3-70B-Instruct-8bit"
revision = "c5bfd839cd4cda0e5a39a97e00218d9c56e468af"
n_layers = 80
hidden_size = 8192
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "8bit"
base_model = "Llama 3.3 70B"
capabilities = ["text"]

[storage_size]
in_bytes = 76799803392
