model_id = "mlx-community/Llama-3.2-3B-Instruct-4bit"
revision = "7f0dc925e0d0afb0322d96f9255cfddf2ba5636e"
n_layers = 28
hidden_size = 3072
supports_tensor = true
tasks = ["TextGeneration"]
family = "llama"
quantization = "4bit"
base_model = "Llama 3.2 3B"
capabilities = ["text"]

[storage_size]
in_bytes = 1863319552
