model_id = "mlx-community/Qwen3-Coder-Next-5bit"
revision = "1f3e27b1c376095ebf88a8037807c92784c25d66"
n_layers = 48
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
family = "qwen"
quantization = "5bit"
base_model = "Qwen3 Coder Next"
capabilities = ["text", "code"]

[storage_size]
in_bytes = 57657697020
