model_id = "mlx-community/gpt-oss-120b-MXFP4-Q8"
revision = "81e5ac3ad0af6efb1298a8e8c7a10ed2990c137b"
n_layers = 36
hidden_size = 2880
supports_tensor = true
tasks = ["TextGeneration"]
family = "gpt-oss"
quantization = "MXFP4-Q8"
base_model = "GPT-OSS 120B"
capabilities = ["text", "thinking"]

[storage_size]
in_bytes = 70652212224
