model_id = "mlx-community/Qwen3-Next-80B-A3B-Thinking-8bit"
revision = "d093dbe8233828ca0cc420f75466133c542a1e96"
n_layers = 48
hidden_size = 2048
supports_tensor = true
tasks = ["TextGeneration"]
family = "qwen"
quantization = "8bit"
base_model = "Qwen3 Next 80B"
capabilities = ["text", "thinking", "thinking_toggle"]

[storage_size]
in_bytes = 88814387200
