model_id = "exolabs/Qwen-Image-8bit"
revision = "617d15c93a317f4b5cebb766d4638775d002b380"
n_layers = 60
hidden_size = 1
supports_tensor = false
tasks = ["TextToImage"]
uses_cfg = true
family = "qwen-image"
quantization = "8bit"
base_model = "Qwen Image"
capabilities = ["image_gen"]

[storage_size]
in_bytes = 37014734400

[[components]]
component_name = "text_encoder"
component_path = "text_encoder/"
n_layers = 12
can_shard = false

[components.storage_size]
in_bytes = 16584333312

[[components]]
component_name = "transformer"
component_path = "transformer/"
n_layers = 60
can_shard = true
safetensors_index_filename = "diffusion_pytorch_model.safetensors.index.json"

[components.storage_size]
in_bytes = 20430401088

[[components]]
component_name = "vae"
component_path = "vae/"
can_shard = false

[components.storage_size]
in_bytes = 0
