model_id = "exolabs/Qwen-Image-Edit-2509-4bit"
n_layers = 60
hidden_size = 1
supports_tensor = false
tasks = ["ImageToImage"]
uses_cfg = true
family = "qwen-image"
quantization = "4bit"
base_model = "Qwen Image Edit"
capabilities = ["image_edit"]

[storage_size]
in_bytes = 26799533856

[[components]]
component_name = "text_encoder"
component_path = "text_encoder/"
n_layers = 12
can_shard = false

[components.storage_size]
in_bytes = 16584333312

[[components]]
component_name = "transformer"
component_path = "transformer/"
n_layers = 60
can_shard = true
safetensors_index_filename = "diffusion_pytorch_model.safetensors.index.json"

[components.storage_size]
in_bytes = 10215200544

[[components]]
component_name = "vae"
component_path = "vae/"
can_shard = false

[components.storage_size]
in_bytes = 0
