[package]
name = "networking"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
doctest = false
name = "networking"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
# datastructures
either = { workspace = true }

# macro dependencies
extend = { workspace = true }
delegate = { workspace = true }

# async
async-stream = { workspace = true }
futures-lite = { workspace = true }
futures-timer = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# utility dependencies
util = { workspace = true }
tracing-subscriber = { version = "0.3.19", features = ["default", "env-filter"] }
keccak-const = { workspace = true }

# tracing/logging
log = { workspace = true }

# networking
libp2p = { workspace = true, features = ["full"] }
pin-project = "1.1.10"
