[package]
name = "networking"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
doctest = false
name = "networking"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
# async
tokio = { workspace = true, features = ["full"] }

# utility dependencies
tracing-subscriber = { version = "0.3.19", features = ["default", "env-filter"] }

# tracing/logging
log = { workspace = true }

# networking
libp2p = { workspace = true, features = ["full"] }
