[package]
name = "networking"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
name = "networking"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
# macro dependencies
extend = { workspace = true }

# async
tokio = { workspace = true, features = ["full"] }
futures-lite = { workspace = true }

# utility dependencies
tracing-subscriber = { version = "0.3.19", features = ["default", "env-filter"] }
keccak-const = { workspace = true }

# tracing/logging
log = { workspace = true }

# networking
libp2p = { workspace = true, features = ["full"] }
