[package]
name = "fn_pipe"
version = { workspace = true }
edition = { workspace = true }
publish = false

[lib]
doctest = false
name = "fn_pipe"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
fn_pipe_proc = { workspace = true }