name: ci-pipeline

on:
  push:
  pull_request:
    branches:
      - staging
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        name: Configure Cachix
        with:
          name: exo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Load nix develop environment
        run: nix run github:nicknovitski/nix-develop/v1

      - name: Sync dependencies
        run: uv sync --all-packages

      - name: Run type checker
        run: uv run basedpyright --project pyproject.toml

  nix:
    name: Build and check (${{ matrix.system }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: macos-26
            system: aarch64-darwin
          - runner: ubuntu-latest
            system: x86_64-linux
          - runner: ubuntu-24.04-arm
            system: aarch64-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        name: Configure Cachix
        with:
          name: exo
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build all Nix outputs
        run: |
          nix flake show --json | jq -r '
            [
              (.packages."${{ matrix.system }}" // {} | keys[] | ".#packages.${{ matrix.system }}.\(.)"),
              (.devShells."${{ matrix.system }}" // {} | keys[] | ".#devShells.${{ matrix.system }}.\(.)")
            ] | .[]
          ' | xargs nix build

      - name: Run nix flake check
        run: nix flake check
